### PR TITLE
update all packages, make code compatible, align ux to lnm default

### PR DESCRIPTION
**Pull request by u-an-i**
**following _issues_ exist**: littlenavmap is not exposed in DOM, attribution on every tile, initial view has 1 wrong zoomed tile 
  
i have not managed to resolve them or find a hint about how on the web

### CODE REVIEW

**Comment by u-an-i** [comment]
retargeting branch coming up

**Comment by KOKAProduktion** [comment]
> **following _issues_ exist**: littlenavmap is not exposed in DOM, attribution on every tile, initial view has 1 wrong zoomed tile
> 
> i have not managed to resolve them or find a hint about how on the web

Hi @u-an-i,

Is this still an issue? As far as I remember I have exposed the OL API by the [ol/Map](https://openlayers.org/en/latest/apidoc/module-ol_Map.html) object via the `littlenavmap.map` var

Cheers!

**Comment by u-an-i** [comment]
hi @KOKAProduktion , no, no issue. I branched from the old master branch.

**Comment by KOKAProduktion** [comment]
Ah ok, sry I have forgotten that `feature/lnm-webapi` branch was the current one...

Thanks!

**Pull request closed without merging**
