### PR TITLE
feature/lnm-webapi

### LINKED ISSUE #2: Crash/blank page upon sim data retrieval : LNM 2.7.8.develop aircraft progress coordinates display turned off by default
However i've found another issue while testing this prototype with the latest LNM version:

- LNM 2.7.8.develop 
- MSFS 1.22.2.0

Aircraft progress coordinates display appears to be turned off by default since LNM 2.7.8 causing the OL prototype to crash as soon as sim data is coming in.

To fix this I had to check on "Coordinates" at Tools -> Progress Display Options:

Screenshot (173)

Screenshot (174)

Hope this helps too... :)

Cheers!

_Originally posted by @KOKAProduktion in https://github.com/KOKAProduktion/msfs2020-littlenavmap-openlayers/issues/1#issuecomment-1045686608_

### PR DESCRIPTION
**Pull request by KOKAProduktion**
Make compatible with https://github.com/albar965/littlenavmap/pull/788

### CODE REVIEW

**Comment by albar965** [comment]
Gimme a ping if I can merge or if you'd like to add more changes.

**Comment by KOKAProduktion** [comment]
Yep, i will! The same applies here: https://github.com/albar965/littlenavmap/pull/788#issuecomment-934681828

Thanks and cheers!

**Comment by KOKAProduktion** [comment]
Compatible to https://github.com/albar965/littlenavmap/pull/826

**Comment by KOKAProduktion** [comment]
Hi @u-an-i ,

sry :) I've put that in the commit message. Here again as a comment:

awesome! Thank you for the updates and the feature!

As far as i can see albar965/littlenavmap/src/webapi is already rolled out since 2.8 so i could basically merge https://github.com/KOKAProduktion/littlenavmap-openlayers/pull/1 into master too, right?

Once again, thanks a lot!
Cheers!

**Comment by u-an-i** [comment]
yes @KOKAProduktion ! :)

**Pull request merged**
